# Generated by Django 3.1.7 on 2021-03-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField(default=0)),
                ('item_status', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
