# Generated by Django 3.1.7 on 2021-03-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='item_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
