# Generated by Django 3.1.7 on 2021-03-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210303_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
